name: publish

on:
  push:
    branches: [ release/** ]

jobs:
  publish_nuget_package:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch code
      uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: | 
          3.1.x
          5.0.x
          6.0.x
    - name: Pack package
      run: dotnet pack "./CSharp/FrameRateTask/FrameRateTask.csproj" -c Release
    - name: Push nuget package
      run: dotnet nuget push "./CSharp/FrameRateTask/bin/Release/*.nupkg"  --api-key ${{ secrets.NUGET_KEY }} --source "https://api.nuget.org/v3/index.json"
